/*
 * Main.java
 *
 * Created on 04. Oktober 2006, 09:30
 */

package multipdfsigner;

import java.io.IOException;
import java.io.OutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.ByteArrayInputStream;
import java.io.FileInputStream;
import java.io.ByteArrayInputStream;
import java.text.AttributedCharacterIterator;
import java.util.*;
import java.security.*;
import java.security.cert.*;


import com.lowagie.text.pdf.PdfReader;
import com.lowagie.text.pdf.PdfWriter;
import com.lowagie.text.pdf.PdfStamper;
import com.lowagie.text.pdf.PdfSigGenericPKCS;
import com.lowagie.text.pdf.PdfLiteral;
import com.lowagie.text.pdf.PdfName;
import com.lowagie.text.pdf.PdfPKCS7;
import com.lowagie.text.pdf.PdfDictionary;
import com.lowagie.text.pdf.PdfString;
import com.lowagie.text.pdf.PdfSignatureAppearance;

/**
 *
 * @author  Patrick hagelkruys
 * @mail patrick.hagelkruys@a-trust.at 
 */
public class Main extends javax.swing.JFrame {
    
    String path = "";
    ArrayList keys;
    ArrayList keystores;    
    class item
    {
        X509Certificate publicKey;
        PrivateKey privateKey;
        java.security.cert.Certificate[] certChain;
        String providerString;
        String pkcs11config;
        
        item(String _providerstring,String _pkcs11config, X509Certificate _publicKey, PrivateKey _privateKey, java.security.cert.Certificate[] _certChain)
        {
            pkcs11config = _pkcs11config;
            providerString = _providerstring;
            publicKey = _publicKey;
            privateKey = _privateKey;
            certChain = _certChain;
        }
    }    
    
    /** Creates new form Main */
    public Main() {
        
        path = System.getProperty("user.dir");
        
        try
        {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        }
        catch(Exception e)
        {}        
        
        initComponents();
        
        keys = new ArrayList();
        keystores = new ArrayList();
        jList1.setModel(new javax.swing.DefaultListModel());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jDialog1 = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jDialog1.setTitle("Zertifikatsauswahl");
        jDialog1.setAlwaysOnTop(true);
        jDialog1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                jDialog1WindowActivated(evt);
            }
        });

        jList2.setFont(new java.awt.Font("Verdana", 0, 10));
        jList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jList2);

        jButton5.setFont(new java.awt.Font("Verdana", 0, 10));
        jButton5.setText("OK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12));
        jLabel6.setText("Bitte w\u00e4hlen Sie ein Zertifikat aus");

        jButton6.setFont(new java.awt.Font("Verdana", 0, 10));
        jButton6.setText("Abbruch");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jDialog1Layout = new org.jdesktop.layout.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jDialog1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel6)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jDialog1Layout.createSequentialGroup()
                        .add(jButton6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton5)))
                .addContainerGap())
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel6)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jDialog1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton5)
                    .add(jButton6))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("a.trust Multi Pdf Signer");
        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12));
        jLabel1.setText("Folgende PDFs werden signiert:");

        jList1.setFont(new java.awt.Font("Verdana", 0, 10));
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        jButton1.setFont(new java.awt.Font("Verdana", 0, 10));
        jButton1.setText("Hinzuf\u00fcgen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Verdana", 0, 10));
        jButton2.setText("Entfernen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12));
        jLabel3.setText("Erweiterte PDF Eigenschaften:");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 10));
        jLabel4.setText("Grund der Signatur:");

        jTextField3.setFont(new java.awt.Font("Verdana", 0, 10));
        jTextField3.setText("Ich bin der Autor");

        jTextField4.setFont(new java.awt.Font("Verdana", 0, 10));
        jTextField4.setText("\u00d6sterreich");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 10));
        jLabel5.setText("Ort der Signatur:");

        jButton4.setFont(new java.awt.Font("Verdana", 0, 10));
        jButton4.setText("Signieren");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Verdana", 0, 10));
        jButton3.setText("Beenden");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                                        .add(246, 246, 246)
                                        .add(jButton2)))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 96, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 96, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 432, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel4)
                            .add(jLabel5))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 154, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(293, 293, 293))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton2)
                    .add(jButton1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(jTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton3))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 451, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDialog1WindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialog1WindowActivated
// TODO add your handling code here:
        
        javax.swing.DefaultListModel listModel = new javax.swing.DefaultListModel();
        
        for( int i=0; i < keys.size(); i++) {
            item temp = (item) keys.get(i);
            String id = temp.publicKey.getSubjectDN().toString();
            int i1 = id.toLowerCase().indexOf("cn=")+3;
            int i2 = id.indexOf(",",i1);
            String name = id.substring(i1,i2);
            i1 = id.toLowerCase().indexOf("serialnumber=")+13;
            i2 = id.indexOf(",",i1);
            name = name +", "+id.substring(i1,i2) +", "+ temp.publicKey.getSerialNumber().toString();
            System.out.println(id);
            
            listModel.add(i,name);
        }
        jList1.setModel(listModel);
        jList1.setSelectedIndex(0);
    }//GEN-LAST:event_jDialog1WindowActivated

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
// TODO add your handling code here:
        jDialog1.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
// TODO add your handling code here:
        jDialog1.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        // Beenden
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:    
        // Signieren
        
        boolean error = false;
        int slots = 4;
        String library = path+"\\asignp11.dll";
        getAllCerts(library,slots);
        
        int index = 0;
        if (keys.size() <= 0)
        {
            javax.swing.JOptionPane.showMessageDialog(this,"Es wurde keine passende Signaturkarte gefunden!","Fehler", javax.swing.JOptionPane.ERROR_MESSAGE);
            error = true;
        }
        else if (keys.size() > 1)
        {
            // Dialog zu Signaturkartenauswahl einblenden
            jDialog1.pack();
            jDialog1.setModal(true);
            jDialog1.setVisible(true);
            
            index = jList1.getSelectedIndex();
        }
        
        if(error == false)
        {
            item choice = (item)keys.get(index);
            javax.swing.DefaultListModel dlm = (javax.swing.DefaultListModel) jList1.getModel();
        
            byte[] pkcs11configBytes = choice.pkcs11config.getBytes();
            ByteArrayInputStream configStream = new ByteArrayInputStream(pkcs11configBytes);
            Provider pkcs11Provider = new sun.security.pkcs11.SunPKCS11(configStream);
            Security.addProvider(pkcs11Provider);
            
            for(int i = 0; i < dlm.size() ;i++)
            {
                String path = (String) dlm.get(i);
                String path2 = path.replace(".pdf","_signed.pdf");
                signPDF(path,path2,choice);
            }
            
            Security.removeProvider(choice.providerString);
        }
        
        keystoreclean();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    
    private boolean signPDF(String input,String output,item choice)
    {
        // signieren
        PdfReader reader;
        try
        {
            reader = new PdfReader(input);
        }
        catch(Exception e)
        {
            javax.swing.JOptionPane.showMessageDialog(this,"Auf die zu signierenden PDF Datei kann nicht zugegriffen werden!","Fehler", javax.swing.JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        java.io.FileOutputStream fout;
        try
        {
            fout = new java.io.FileOutputStream(output);
        }
        catch (Exception e)
        {
            return false;
        }        

        try
        {
                 
            PdfStamper stp = PdfStamper.createSignature(reader, fout, '\0');
            PdfSignatureAppearance sap = stp.getSignatureAppearance();
            sap.setProvider("SunPKCS11-"+choice.providerString);
            sap.setCrypto(choice.privateKey, choice.certChain, null, PdfSignatureAppearance.WINCER_SIGNED);
            sap.setReason(jTextField3.getText());
            sap.setLocation(jTextField4.getText());
            stp.close();                                

            
        }
        catch(Exception e)
        {
            return false;
        }
        
        return true;
    }
    
    
    private void keystoreclean()
    {       
        keys.clear();
    }      
    
    private void getAllCerts(String library,int slots)
    {
        for(int i=0; i <= slots; i++)
        {
            KeyStore smartCardKeyStore;
            String providerstring = "asignp11_"+i;
            String pkcs11config = "name ="+providerstring+"\nlibrary = "+library+"\nslot="+i+"\n";
            System.out.println(pkcs11config);
            byte[] pkcs11configBytes = pkcs11config.getBytes();
            ByteArrayInputStream configStream = new ByteArrayInputStream(pkcs11configBytes);
            
            try
            {
                Provider pkcs11Provider = new sun.security.pkcs11.SunPKCS11(configStream);
                Security.addProvider(pkcs11Provider);
            
                smartCardKeyStore = KeyStore.getInstance("PKCS11",pkcs11Provider);
                smartCardKeyStore.load(null, null);
                
                keystores.add(providerstring);
                
                Enumeration aliasesEnum = smartCardKeyStore.aliases();
                while (aliasesEnum.hasMoreElements())
                {
                    
                    String alias = (String)aliasesEnum.nextElement();
                    System.out.println(alias);
                    if ( alias.equals("C.CH.EKEY") )
                    {
                        X509Certificate cert = (X509Certificate) smartCardKeyStore.getCertificate(alias);
                        PrivateKey privateKey = (PrivateKey) smartCardKeyStore.getKey(alias, null);                    
                        java.security.cert.Certificate[] chain = smartCardKeyStore.getCertificateChain(alias);
                        
                        item key =  new item(providerstring,pkcs11config,cert,privateKey,chain);
                        keys.add(key);
                    }
                }//ende while
                
                Security.removeProvider(providerstring);
            }
            catch(Exception e)
            {
                //e.printStackTrace();
            }
        }// ende for        
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        int index = jList1.getSelectedIndex();
        if (index >= 0)
        {
            javax.swing.DefaultListModel dlm = (javax.swing.DefaultListModel) jList1.getModel();
            dlm.remove(index);
            jList1.setModel(dlm);       
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // PDF Hinzufügen
        
        javax.swing.JFileChooser fc = new javax.swing.JFileChooser();
        fc.setDialogType(javax.swing.JFileChooser.OPEN_DIALOG);
        fc.setDialogTitle("Welche PDF Dateien sollen signiert werden?");
        fc.setMultiSelectionEnabled(true);
        fc.setFileFilter(new javax.swing.filechooser.FileFilter(){
                public boolean accept(java.io.File f) {
                    return f.getName().toLowerCase().endsWith(".pdf") || f.isDirectory();
                }
                public String getDescription() {
                    return "PDF Datei (*.pdf)";
                }
            }
        );
        
        java.io.File[] selectedFiles;    
        
        if (fc.showOpenDialog(null) == javax.swing.JFileChooser.APPROVE_OPTION) 
        {
            selectedFiles = fc.getSelectedFiles();
        }
        else
        {
            return;
        }
        
        
        javax.swing.DefaultListModel dlm = (javax.swing.DefaultListModel) jList1.getModel();
        for(int i=0; i < selectedFiles.length;i++)
        {
            String path = selectedFiles[i].getAbsolutePath();
            
            if ( dlm.indexOf((Object)path) < 0)
            {
                dlm.addElement((Object)path);
            }
        } 
        
        jList1.setModel(dlm);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
    
}
